Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (386,'Tara Hategului','Paucinesti, com. Sarmizegetusa, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (387,'Tara Hategului','Nadastia de Jos; orasul Calan, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (388,'Gorj','Dobrita, com. Runcu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (389,'Tara Hategului','Baiesti, com. Pui, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (390,'Marginimea Sibiului','Rau Sadului, com. Rau Sadului, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (391,'Marginimea Sibiului','Rasinari, com. Rasinari, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (392,'Muntii Apuseni','orasul Abrud, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (393,'Gorj','Sarbesti, com. Musetesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (394,'Bistrita','com. Sebis, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (395,'Tinutul Secuiesc','com. Zetea, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (396,'Tinutul Secuiesc','Belani, com. Poian, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (397,'Tinutul Secuiesc','Armaseni, com. Ciucsangeorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (398,'Tinutul Secuiesc','Albis, com. Cernat, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (399,'Tara Lapusului','Dumbrava; orasul Targu Lapus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (400,'Lapus','Cupseni, com. Cupseni, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (401,'Tara Chioarului','Aspra, com. Vima Mica, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (402,'Campia Transilvaniei','Mura Mare (Iara de Mures); com. Gornesti, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (403,'Valcea','Muereasca de Sus, com. Muereasca, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (404,'Valcea','Sinesti, com. Sinesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (405,'Valea Bistritei','Bicaz-Chei, com. Bicaz-Chei, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (406,'Valcea','Mitrofani, Racu, com. Sutesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (407,'Gurghiu','Hodac, com. Hodac, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (408,'Prahova','orasul Valenii de Munte, jud. Prahova');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (409,'Campulung Moldovenesc','oras Campulung Moldovenesc, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (410,'Neamt','Audia, com. Hangu, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (411,'Vrancea','Popesti, com. Urechesti, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (412,'Muscel','Huluba, com. Hartiesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (413,'Campia Transilvaniei','Dumitra, com. Santimbru, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (414,'Vrancea','Paltin, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (415,'Marginimea Sibiului','Tilisca, com. Tilisca, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (416,'Buzau','Chiojdu Mic, com. Chiojd, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (417,'Dobrogea de nord','Jurilovca, com. Jurilovca, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (418,'Lapus','Surdesti, com. Sisesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (419,'Dobrogea de nord','Visina, com. Jurilovca, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (420,'Muntii Apuseni','Avram Iancu, com. Avram Iancu, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (421,'Muntii Apuseni','com. Marisel, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (422,'Nasaud','com. Romuli, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (423,'Radauti','Bilca, com. Bilca, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (424,'Suceava, subzona Campulung Moldovenesc','Vama, com. Vama, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (425,'Maramures','com. Vad, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (426,'Campulung Moldovenesc','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (427,'Humor','Cacica, com. Cacica, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (428,'Gorj','orasul Targu-Carbunesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (429,'Gorj','com. Pades, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (430,'Gorj','Curtisoara, com. Bumbesti - Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (431,'Bistrita','Jelna, com. Budacu de Jos, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (432,'Lugoj','Satu Mic, com. Victor Vlad Delamarina, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (433,'Caras','Constantin Daicoviciu, com. Constantin Daicoviciu, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (434,'Maramures','com. Salistea, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (435,'Tinutul Secuiesc','Fitod, com. Sancraieni, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (436,'Covasna-Harghita','Potiond, com. Ciucsangiorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (437,'Tinutul Secuiesc , Covasna-Harghita','Potiond, com. Armaseni, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (438,'Maramures','com. Sapanta, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (439,'Tinutul Secuiesc','Joseni, com. Joseni, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (440,'Valea Izei','com. Campulung la Tisa, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (441,'Dobrogea de sud','Bugeac, com. Adamclisi, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (442,'Valcea','Ladesti, Locul "Serana", com. Ladesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (443,'Suceava','Zapodeni, com. Zapodeni, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (444,'Maramures (subzona Cosaului)','com. Calinesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (445,'Mara – Cosau, Iza inferioara','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (446,'Maramures','Valeni, com. Calinesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (447,'Suceava','Moldovita, com. Moldovita, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (448,'Tara Oltului','Sebesu de Jos, com. Turnu Rosu, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (449,'Dobrogea','Chirnogeni, com. Chirnogeni, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (450,'Neamt','Poiana Teiului, com. Poiana Teiului, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (451,'Bran','Simon, Gura Simonului, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (452,'Bran','Pestera, Poiana Stanii, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (453,'Bran','Poarta, Muchia Jigaretilor, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (454,'Valcea','Prundeni, com. Prundeni, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (455,'Valcea','Milcoiu, Gibesti, com. Milcoiu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (456,'Vrancea','Romanesti, com. Nistoresti, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (457,'Marginimea Sibiului','Obarsia, com. Saliste, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (458,'Crisul Repede','Suncuius, com. Suncuius, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (459,'Valcea','Munteni, com. Mihaesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (460,'Zarand','Obarsa, com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (461,'Dambovita','Manesti, com. Manesti, jud. Dambovita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (462,'Gorj','Polovragi, com. Polovragi, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (463,'Arad','Capalnas, com. Capalnas, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (464,'Gorj','Paraul de Pripor, com. Ciuperceni, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (465,'Gorj','Borosteni, com. Pestisani, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (466,'Alba','Fenes, com. Metes, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (467,'Salaj','Taudu, com. Almasu, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (468,'Zarand','Livada, com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (469,'Almaj','Toplet, com. Toplet, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (470,'Valea Muresului superior','com. Vatava, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (471,'Muscel','Podul Dambovitei, Fantana Dealului, com. Dambovicioara, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (472,'Tinutul Secuiesc','Valcele, com. Valcele, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (473,'Lapus','Lapus, com. Lapus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (474,'Maramures','Giulesti, com. Giulesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (475,'Chioar','Chechis, com. Dumbravita, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (476,'Tara Chioarului','Buteasa, com. Somcuta Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (477,'Campia Transilvaniei','com. Hodosa, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (478,'Valcea','Saliste, com. Malaia, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (479,'Valcea','Otesani, com. Otesani, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (480,'Valcea','Valea Gradistii, com. Gradistea, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (481,'Orastie','Ludestii de Jos, Ludestii de Sus, com. Orastioara de Sus, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (482,'Moldova centrala','orasul Husi, Corni, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (483,'Maramures','Botiza, com. Botiza, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (484,'Suceava','Straja, com. Straja, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (485,'Maramures','com. Berbesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (486,'Neamt','Piatra Soimului, com. Piatra Soimului, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (487,'Nasaud','Sant, com. Sant, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (488,'Valcea','orasul Dragasani, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (489,'Muscel','Vulturesti, com. Hartiesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (490,'Muntii Apuseni','com. Sugag, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (491,'Valcea','Barzoteni, com. Maldaresti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (492,'Maramures','orasul Sighetu Marmatiei, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (493,'Dealurile Clujului','Turea, com. Garbau, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (494,'Romanati','Salcia, com. Argetoaia, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (495,'Podisul Babadag (Podisul Central Dobroge','Enisala, com. Sarichioi, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (496,'Muntii Apuseni','Salciua de Jos, com. Salciua, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (497,'Valea Ariesului','Bucium-Poieni, Bucium-Poieni, com. Bucium, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (498,'Tara Hategului','Salasu de Sus, com. Salasu de Sus, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (499,'Muscel','Stanesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (500,'Podisul Central Moldovenesc','com. Oltenesti, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (501,'Prahova','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (502,'Bistrita','Orhei, com. Cetate, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (503,'Alba','com. Ighiu, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (504,'Suceava','Partestii de Jos, com. Partesti, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (505,'Suceava, subzona etnografica Falticeni','Malini, com. Malini, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (506,'Falticeni','Radaseni, com. Radaseni, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (507,'Alba','com. Galda de Sus, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (508,'Campulung Moldovenesc','Rasca, com. Moldovita, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (509,'Valcea','Mangureni, Isbasesti, com. Nicolae Balcescu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (510,'Hunedoara','Bejan, com. Soimus, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (511,'Arad','Grosii Noi, com. Barzava, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (512,'Campia Transilvaniei','Geaca, com. Geaca, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (513,'Tara Lapusului','Plopis, com. Plopis-Sisesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (514,'Bihor','Leheceni, com. Carpinet, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (515,'Campia Timisului','Babsa, Colonia Maghiara, com. Belint, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (516,'Faget','Zolt, com. Fardea, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (517,'Campia Timisului','Babsa, com. Belint, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (518,'Tinutul Secuiesc','com. Ciucsangeorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (519,'Tinutul Secuiesc','Ineu, com. Carta, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (520,'Tulcea','Jurilovca, com. Jurilovca, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (521,'Maramures','com. Saliste, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (522,'Gorj','Arcani, com. Arcani, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (523,'Bran','Simon, Paraul Arzoilor, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (524,'Valcea','Tomsani, com. Tomsani, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (525,'Dobrogea de nord','Dunavatu de Jos, com. Murighiol, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (526,'Bucovina','jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (527,'Buzau','Alunis, com. Colti, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (528,'Podisul Tarnavelor','Sasaus, com. Chirpar, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (529,'Maramures','Berbesti, com. Giulesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (530,'Husi','Arsura, com. Arsura, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (531,'Gorj','Miculesti, com. Slivilesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (532,'Gorj','Baia de Fier, com. Baia de Fier, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (533,'Gorj','Bradiceni, com. Pestisani, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (534,'Maramures','Sapanta, com. Sapanta, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (535,'Bihor','Suncuius, com. Suncuius, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (536,'Dealurile Clujului','Geaca, com. Geaca, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (537,'Valea Muresului superior','com. Subcetate, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (538,'Valea Muresului superior','com. Ciobotani, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (539,'Maramures','Harnicesti, com. Desesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (540,'Maramures','Borsa, com. Borsa, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (541,'Tara Chioarului','Prislop, com. Boiu Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (542,'Maramures','Bogdan Voda, com. Bogdan Voda, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (543,'Maramures','Petrova, com. Petrova, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (544,'Campia Transilvaniei','Ardan, com. Sieu, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (545,'Valcea','Barbatesti, com. Barbatesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (546,'Valcea','Malaia, Muntele Smeurat, com. Malaia, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (547,'Valcea','Zmeurat, Cacova, com. Stoienesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (548,'Valcea','Cernisoara, com. Cernisoara, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (549,'Maramures','Feresti - Berbesti, com. Giulesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (550,'Prahova','Batrani, com. Starchiojd, jud. Prahova');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (551,'Orastie','Art, Între paraua, com. Sugag, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (552,'Muntii Apuseni','Sugag, com. Sugag, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (553,'Gorj','Glodeni, com. Balanesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (554,'Buzau','com. Chiojd, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (555,'Valcea','com. Glavile, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (556,'Oltenia','Ciorasti, com. Glodeni, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (557,'Maramures','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (558,'Maramures','Dragomiresti, com. Dragomiresti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (559,'Tara Hategului','Paros, com. Salasu de Sus, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (560,'Bucovina','Fundu Moldovei, com. Fundu Moldovei, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (561,'Lapus','Ciolt, com. Somcuta Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (562,'Tara Oasului','Camarzana, com. Camarzana, jud. Satu Mare');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (563,'Campulung Moldovenesc','Moldovita, com. Moldovita, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (564,'Suceava','Manastirea Humorului, com. Manastirea Humorului, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (565,'Suceava','Batca Pripor, com. Dorna Candrenilor, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (566,'Suceava','Rosu; orasul Vatra Dornei, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (567,'Radauti','Breaza, com. Breaza, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (568,'Suceava','com. Manastirea Humorului, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (569,'Alba','Galda de Sus, com. Galda de Jos, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (570,'Zarand','com. Almas, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (571,'Arges','Stanesti, com. Corbi, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (572,'Arad','Julita, com. Varadia de Mures, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (573,'Dealurile Clujului','Lita, com. Savadisla, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (574,'Muntii Apuseni','Marisel, com. Marisel, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (575,'Campia Timisului','com. Jebel, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (576,'Valea Muresului','Capalnas, com. Birchis, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (577,'Caras','Cavaran, com. Constantin Daicoviciu, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (578,'Lugoj','Babsa, com. Belint, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (579,'Banat','Jupanesti, com. Faget, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (580,'Maramures','Oncesti, com. Barsana, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (581,'Tinutul Secuiesc','jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (582,'Zarand','Tebea, com. Baia de Cris, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (583,'Maramures','com. Campulung la Tisa, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (584,'Maramures','Mara, com. Desesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (585,'Maramures','com. Rona de Sus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (586,'Suceava','Vama, com. Vama, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (587,'Radauti','Satu Mare, com. Satu Mare, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (1,'Muscel','Coltii Giuvalei, com. Rucar, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (2,'Bihor','Poienii de Jos, com. Buntesti, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (3,'Bran','Sohodol, Valea Sohodolului, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (4,'Bran','Pestera, Muntele Vladusca, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (5,'Vrancea','Nistoresti, com. Nistoresti, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (6,'Bran','Moeciu de Sus, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (7,'Marginimea Sibiului','Saliste, com. Saliste, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (8,'Tara Lovistei','Racovita, com. Racovita, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (9,'Padureni','Roscani, com. Dobra, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (10,'Bucovina','Straja, com. Straja, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (11,'Vrancea','Sahastru, com. Nereju, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (12,'Gorj','Stolojani, com. Balesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (13,'Muntii Apuseni','Goiesti, com. Vidra, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (14,'Maramures','Calinesti, com. Calinesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (15,'Tarnave','Seica Mare, com. Seica Mare, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (16,'Gorj','Balanesti, com. Balanesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (17,'Sebes','Loman, Tonea, com. Loman, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (18,'Orastie','Grid; orasul Calan, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (19,'Timis','Sanpetru, com. Varias, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (20,'Marginimea Sibiului','Rasinari, Trainei, com. Rasinari, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (21,'Gorj','Rugi, com. Turcinesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (22,'Gorj','Racoti, com. Tismana, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (23,'Gorj','Porceni, com. Bumbesti - Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (24,'Gorj','Musculesti, com. Barbatesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (25,'Salaj','Dragu, com. Dragu, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (26,'Muntii Apuseni','Gura Cornei; orasul Abrud, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (27,'Tarnave','Seleus, com. Danes, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (28,'Tarnave','Bagaciu, com. Bagaciu, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (29,'Campia Transilvaniei','com. Batos, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (30,'Toplita-Deda','Calimanel; orasul Toplita, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (31,'Bistrita','com. Rustior, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (32,'Tinutul Secuiesc','Alungeni, com. Turia, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (33,'Tara Chioarului','Preluca Noua, com. Copalnic-Manastur, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (34,'Maramures','Desesti, com. Desesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (35,'Chioar','Fericea, com. Valea Chioarului, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (36,'Codru','Valea Vinului, com. Valea Vinului, jud. Satu Mare');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (37,'Valcea','Magura, com. Mihaesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (38,'Valcea','Olteanca, com. Glavile, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (39,'Valcea','Maldarestii de Sus, com. Maldaresti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (40,'Maramures','Piatra, com. Remeti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (41,'Zarand','Livada (v.d.Stramba); com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (42,'Sibiu','Cacova, com. Saliste, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (43,'Neamt','Rapciuni, com. Ceahlau, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (44,'Dolj','Ostroveni, com. Ostroveni, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (45,'Muscel','Stanesti, com. Corbi, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (46,'Muscel','jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (47,'Arges','com. Botesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (48,'Tara Hategului','jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (49,'Arges','Cuca - Macai, com. Cuca, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (50,'Oltenia','com. Dragoieni, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (51,'Tara Vrancei','Romanesti, com. Nistoresti, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (52,'Tara Vrancei','Podul Narujei, com. Naruja, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (53,'Podisul Sucevei','Dumbraveni, com. Dumbraveni, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (54,'Ilfov','Ghermanesti, com. Snagov, jud. Ilfov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (55,'Gorj','Timiseni, Boncea, com. Farcasesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (56,'Podisul Central Moldovenesc','Zapodeni, com. Zapodeni, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (57,'Muntii Apuseni','Lazesti, com. Scarisoara, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (58,'Valea Teregovei','Teregova, com. Teregova, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (59,'Arad','Cherelus, com. Sicula, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (60,'Gorj','Ceauru, com. Balesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (61,'Muntii Apuseni','Costesti, com. Poiana Vadului, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (62,'Tara Oasului','Moiseni, com. Certeze, jud. Satu Mare');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (63,'Tinutul Secuiesc','Imper, com. Plaiesii de Jos, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (64,'Muntii Apuseni','Margau, com. Margau, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (65,'Tinutul Secuiesc','Casinu Nou, com. Plaiesii de Jos, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (66,'Nasaud','com. Telciu, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (67,'Radauti','com. Straja, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (68,'Campulung Moldovenesc','orasul Campulung Moldovenesc, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (69,'Bucovina','Bilca, com. Bilca, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (70,'Campulung Moldovenesc','Holohosca, com. Sadova, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (71,'Gorj','Bumbesti-Jiu, com. Bumbesti-Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (72,'Gorj','Closani, Poienile de Sus, com. Pades, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (73,'Hunedoara','Lunca Motilor, com. Baia de Cris, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (74,'Salaj','Cizer, com. Cizer, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (75,'Muntii Apuseni','Rimetea, com. Rimetea, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (76,'Bargaie','Josenii Bargaului, com. Josenii Bargaului, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (77,'Maramures','com. Dragomiresti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (78,'Maramures','com. Sacel, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (79,'Maramures','Campulung la Tisa, com. Campulung la Tisa, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (80,'Tinutul Secuiesc , Covasna-Harghita','Potiond, com. Ciucsangiorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (81,'Arges','Martesti, com. Sapata, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (82,'Tinutul Secuiesc','com. Praid, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (83,'Campia Munteniei','com. Rusetu, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (84,'Maramures','com. Poienile de Sub Munte, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (85,'Maramures','Cracesti - Mara, com. Desesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (86,'Maramures','com. Vadu Izei, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (87,'Maramures','Sarbi, com. Stramtura, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (88,'Radauti','Vicovu de Jos, com. Vicovu de Jos, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (89,'Arges','Satic, com. Rucar, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (90,'Valea Jiului','Campu lui Neag, com. Campu lui Neag, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (91,'Padureni','Dabaca, com. Toplita, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (92,'Clisura Dunarii','Svinita, com. Svinita, jud. Mehedinti');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (93,'Bran','Moeciu de Sus, Valea Popii, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (94,'Valcea','com. Nicolae Balcescu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (95,'Valcea','Valea Bujorencii, com. Bujoreni, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (96,'Muscel','Rucar, com. Rucar, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (97,'Muntii Apuseni','Stanesti, Hanasesti, com. Poiana Vadului, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (98,'Salaj','Mierta, com. Cuzaplac, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (99,'Gurghiu','Ibanesti, com. Hodac, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (100,'Bucovina','orasul Campulung Moldovenesc, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (101,'Olt','Oboga de Sus, com. Oboga, jud. Olt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (102,'Gorj','Valeni, com. Plopsoru, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (103,'Zarand','Rasculita, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (104,'Gorj','Croici, com. Matasari, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (105,'Husi','Curteni, com. Oltenesti, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (106,'Almaj','Prigor, com. Prigor, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (107,'Culoarul Muresului','Almas-Saliste, com. Zam, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (108,'Gorj','Carligei, com. Bumbesti-Pitic, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (109,'Tara Hategului','Grid; orasul Calan, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (110,'Zarand','Ocisor, com. Vata de Jos, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (111,'Tara Lovistei','Mlaceni, com. Perisani, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (112,'Tara Oltului','Turnu Rosu, com. Turnu Rosu, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (113,'Tinutul Secuiesc','Varghis, com. Varghis, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (114,'Tinutul Secuiesc','Cernatul de Sus, com. Cernat, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (115,'Tinutul Secuiesc','Pava, com. Zabala, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (116,'Campia Satmarului','Babesti, com. Halmeu, jud. Satu Mare');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (117,'Lapus','Ungureni, com. Cupseni, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (118,'Lapus','Costeni, com. Cupseni, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (119,'Tara Chioarului','Carpinis, com. Copalnic-Manastur, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (120,'Valea Gurghiului','Orsova, com. Gurghiu, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (121,'Valcea','Boisoara, com. Boisoara, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (122,'Valcea','Mitrofani, com. Sutesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (123,'Valcea','Alunu, com. Alunu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (124,'Gorj','Balanesti, Voitestii de Vale, com. Balanesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (125,'Valcea','Armasesti, com. Cernisoara, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (126,'Buzau','Chiojdul Mic, com. Chiojd, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (127,'Buzau','jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (128,'Banat','Borlova, com. Turnu Ruieni, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (129,'Maramures','com. Ieud, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (130,'Alba','Ighiel, com. Ighiu, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (131,'Tara Hategului','com. Sarmizegetusa, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (132,'Arges','Jugur, com. Poienarii de Muscel, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (133,'Dolj','Puturi, com. Castranova, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (134,'Muscel','com. Davidesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (135,'Tara Vrancei','Sahastru, com. Nereju, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (136,'Valea Milcovului','Raiuti, com. Reghiu, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (137,'Valea Milcovului','Rachitasu, com. Andreiasu, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (138,'Dobrogea','Enisala, com. Sarichioi, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (139,'Buzau','Magura, com. Magura, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (140,'Gorj','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (141,'Romanati','Castranova, com. Castranova, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (142,'Crisul Repede','Varzari, com. Varzari, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (143,'Tara Fagarasului','Dragus, com. Vistea, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (144,'Tara Barsei, subzona Rupea','Mesendorf, com. Bunesti, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (145,'Ilfov','jud. Ilfov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (146,'Tara Hategului','Fizesti, com. Pui, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (147,'Muntii Apuseni','jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (148,'Campulung Moldovenesc','Ostra, com. Ostra, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (149,'Radauti','Straja, com. Straja, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (150,'Maramures','com. Barsana, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (151,'Muntii Apuseni','Almasu Mare, com. Almas, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (152,'Arad','Cil, com. Almas, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (153,'Banat','Zolt, com. Fardea, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (154,'Arad','Zabalt, com. Dorgos, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (155,'Arad','Bulci, com. Bata, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (156,'Maramures','com. Cuhea, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (157,'Banat','oras Timisoara, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (158,'Maramures','com. Sighetul Marmatiei, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (159,'Maramures','Sarbi, com. Budesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (160,'Maramures','com. Salistea de Sus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (161,'Maramures','Poienile Izei, com. Botiza, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (162,'Tinutul Secuiesc','Chileni, com. Suseni, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (163,'Maramures','com. Stramtura, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (164,'Valea Izei','Slatioara, com. Stramtura, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (165,'Valcea','Ladesti, com. Ladesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (166,'Muntii Apuseni','Fenes; orasul Zlatna, Valea Fenesului, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (167,'Dolj','Goicea Mica, com. Goicea, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (168,'Maramures','Feresti, com. Giulesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (169,'Tara Hategului','Rau de Mori, com. Rau de Mori, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (170,'Dambovita','Barbuletu, com. Barbuletu, jud. Dambovita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (171,'Dobrogea de nord','Bestepe, com. Bestepe, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (172,'Dobrogea de nord','Frecatei, com. Frecatei, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (173,'Salaj','Rastoltu Mare, com. Bucium, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (174,'Caras','Sasca Romana, com. Sasca Montana, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (175,'Tinutul Secuiesc','Corund, com. Corund, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (176,'Caras','Carsie, com. Sichevita, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (177,'Campia Timisului','Sanpetru, com. Varias, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (178,'Marginimea Sibiului','Talmacel, com. Talmaciu, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (179,'Gorj','orasul Ticleni, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (180,'Gorj','Balesti, com. Balesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (181,'Gorj','orasul Motru, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (182,'Gorj',' Targu Carbunesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (183,'Tara Motilor','Fagetul de Sus, com. Poiana Vadului, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (184,'Bran','Magura, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (185,'Bihor','Fanate, com. Campani, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (186,'Valea Muresului superior','Galautas-Parau, com. Galautas, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (187,'Valea Gurghiului','Ibanesti, com. Hodac, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (188,'Bran','Cheia, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (189,'Tara Chioarului','Bozanta Mare, com. Tautii Magheraus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (190,'Codru','Basesti, com. Basesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (191,'Codru','Tamasesti, com. Arinis, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (192,'Tara Chioarului','Cicarlau, com. Cicarlau, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (193,'Maramures','com. Petrova, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (194,'Tara Chioarului','Carpinis, com. Carpinis, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (195,'Baia Mare','Baia Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (196,'Lapus','Larga, com. Suciu de Sus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (197,'Codru','Tamaia, com. Farcasa, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (198,'Valea Gurghiului','com. Hodac, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (199,'Valcea','Gaujani, com. Boisoara, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (200,'Valcea','Olteni, com. Bujoreni, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (201,'Valcea','Bunesti, com. Bunesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (202,'Tara Hategului','Gradistea de Munte, Sub cununa 57 (Dealul Cocos); com. Orastioara de Sus, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (203,'Tinutul Secuiesc','Bancu, com. Ciucsangeorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (204,'Neamt','Bistricioara, com. Ceahlau, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (205,'Arges','Albota, com. Albota, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (206,'Dobrogea','com. Ostrov, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (207,'Arges','Dragutesti, com. Cotmeana, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (208,'Tara Vrancei','Spulber, com. Paltin, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (209,'Tara Vrancei','Tulnici, com. Tulnici, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (210,'Vrancea','Naruja, com. Naruja, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (211,'Clisura Dunarii','Plavisevita, Valea Plavisevitei, com. Plavisevita, jud. Mehedinti');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (212,'Maramures','Ocna Sugatag, com. Ocna Sugatag, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (213,'Banat','Sarbova, com. Racovita, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (214,'Gorj','Budieni, com. Scoarta, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (215,'Campia Munteniei','Rusetu, com. Rusetu, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (216,'Lapus','Coas, com. Sacalaseni, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (217,'Dealurile Clujului','Bedeciu, com. Manastireni, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (218,'Salaj','com. Bucium, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (219,'Maramures','com. Calinesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (220,'Zarand','Cil, com. Almas, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (221,'Vatra Dornei','Iacobeni, com. Iacobeni, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (222,'Cluj','com. Marisel, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (223,'Crisul Negru','Varzari, com. Varzari, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (224,'Bran','Pestera, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (225,'Campia Timisului','Sarazani, com. Barna, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (226,'Maramures','Breb, com. Ocna Sugatag, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (227,'Maramures','com. Vadul Izei, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (228,'Tinutul Secuiesc','com. Sanmartin, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (229,'Tinutul Secuiesc','Plaiesii de Sus, com. Plaiesii de Jos, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (230,'necunoscuta','com. Dalnic, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (231,'Tinutul Secuiesc','Sansimion, com. Sansimion, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (232,'Dolj','Dobrisor, com. Motatei, jud. Dolj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (233,'Valea Timis-Cerna, Caransebes','Borlova, com. Turnu-Ruieni, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (234,'Valcea','Feteni, com. Gorani, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (235,'Campulung Moldovenesc','Vama, com. Vama, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (236,'Dobrogea de nord','Mahmudia, com. Mahmudia, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (237,'Cluj','Rogojel, com. Sacuieu, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (238,'Tara Barsei','orasul Codlea, Muntele Dealu Frumos, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (239,'Bran','Simon, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (240,'Radauti','Arbore, com. Arbore, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (241,'Muntii Apuseni','Tomutesti, com. Vadu Motilor, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (242,'Radauti','Marginea, com. Marginea, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (243,'Zarand','Rasculita, com. Baia de Cris, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (244,'Podisul Tarnavelor','Saschiz, com. Saschiz, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (245,'Zarand','Leaut, com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (246,'Alba','Rimetea, com. Rimetea, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (247,'Marginimea Sibiului','jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (248,'Husi','Pahnesti, com. Arsura, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (249,'Salaj','Sancraiu Almajului, com. Sancraiu Almajului, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (250,'Zarand','Tomesti, com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (251,'Marginimea Sibiului','Poiana Sibiului, com. Poiana Sibiului, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (252,'Gurghiu','com. Hodac, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (253,'Bran','Moeciu, Drumul Mic, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (254,'Tara Chioarului','Somcuta Mare, com. Somcuta Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (255,'Zona Chioar','Fericea, com. Valea Chioarului, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (256,'Tara Chioarului','Finteusu Mare, com. Somcuta Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (257,'Tara Chioarului','Fauresti, com. Copalnic-Manastur, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (258,'Valcea','Barlogi, com. Stoenesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (259,'Valcea','Robesti, com. Caineni, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (260,'Valcea','Balteni, com. Copaceni, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (261,'Culoarul Muresului','Cerbia, com. Zam, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (262,'Bucovina','com. Fundu Moldovei, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (263,'Buzau','Ulmu, com. Ulmu, jud. Calarasi');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (264,'Muntenia','jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (265,'Romanati','Draghiceni, com. Draghiceni, jud. Olt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (266,'Prahova','Posestii Pamanteni, com. Posesti, jud. Prahova');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (267,'Tara Vrancei','Campuri, com. Campuri, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (268,'Tara Vrancei','Piscu Radului, com. Vizantea-Livezi, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (269,'Tara Vrancei','Vrancioaia, com. Vrancioaia, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (270,'Neamt','Mastacan, com. Borlesti, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (271,'Suceava','Voitinel, com. Galanesti, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (272,'Dobrogea de sud','Ostrov, com. Ostrov, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (273,'Valcea','Pietrari, com. Pietrari, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (274,'Neamt','com. Piatra Soimului, jud. Neamt');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (275,'Valea Prahovei','Traisteni, com. Valea Doftanei, jud. Prahova');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (276,'Vrancea','Nereju Mic, com. Nereju, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (277,'Delta Dunarii (sud)','Valea Nucarilor, În poiana, com. Valea Nucarilor, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (278,'Campulung Moldovenesc','Breaza de Sus, com. Breaza, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (279,'Campulung Moldovenesc','com. Breaza, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (280,'Maramures','Ieud, com. Ieud, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (281,'Muntii Apuseni','Dealul Botii, com. Maragau, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (282,'Nasaud','jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (283,'Suceava','jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (284,'Alba','Stremt, com. Stremt, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (285,'Suceava','Saru Dornei, com. Saru Dornei, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (286,'Gorj','Olari, com. Plopsoru, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (287,'Gorj','Porceni, com. Bumbesti-Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (288,'Arad','Troas, com. Savarsin, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (289,'Muntii Apuseni','Bucium-Poieni, com. Bucium, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (290,'Campia Transilvaniei','Sucutard, com. Geaca, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (291,'Campia Timisului','com. Barna, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (292,'Maramures','com. Oncesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (293,'Tinutul Secuiesc','Ciucsangeorgiu, com. Ciucsangeorgiu, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (294,'Tinutul Secuiesc','Racu, com. Siculeni, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (295,'Apuseni','Salciua de Jos, com. Salciua, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (296,'Podisul Babadag (Podisul Central Dobroge','Sarichioi, com. Sarichioi, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (297,'Maramures','com. Poienile de sub Munte, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (298,'Campulung','Vama, com. Vama, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (299,'Campia Timisului','Cerna, com. Liebling, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (300,'Maramures','Rozavlea, com. Rozavlea, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (301,'Maramures','Remetea Chioarului, com. Remetea Chioarului, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (302,'Marginimea Sibiului','Rasinari, Dealul Darjani, com. Rasinari, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (303,'Dobrogea','Topalu, com. Topalu, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (304,'Gorj','Galesoaia, com. Calnic, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (305,'Bran','Poarta, Muchia Jigarii, com. Bran, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (306,'Valcea','Stoenesti, com. Stoenesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (307,'Valcea','Maldaresti de Jos, com. Maldaresti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (308,'Marginimea Sibiului','Gura Raului, com. Gura Raului, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (309,'Tara Hategului','Ohaba-Sibisel, com. Rau de Mori, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (310,'Dobrogea de nord','Enisala, com. Sarichioi, jud. Tulcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (311,'Maramures','Lucacesti, com. Pribilesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (312,'Tinutul Secuiesc','com. Tulghes, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (313,'Valcea','orasul Horezu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (314,'Maramures','Sacel, com. Sacel, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (315,'Gorj','Petresti, com. Barbatesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (316,'Gorj','Romanesti; orasul Targu Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (317,'Gorj','Timiseni, com. Farcasesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (318,'Gorj','Curtisoara, com. Bumbesti-Jiu, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (319,'Marginimea Sibiului','Rod, com. Tilisca, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (320,'Tarnave','Saschiz, com. Saschiz, jud. Mures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (321,'Bistrita','com. Teaca, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (322,'Bran','Cheia, Coltul Cheii, com. Moeciu, jud. Brasov');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (323,'Tara Chioarului','Firiza; orasul Baia Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (324,'Tara Chioarului','Chechis, com. Dumbrava, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (325,'necunoscuta','Seini, com. Seini, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (326,'Lapus','com. Lapus, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (327,'Valcea','Turcesti, com. Mateesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (328,'Valcea','Giulesti, Popesti, com. Fartatesti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (329,'Valcea','Maldarestii de Jos, com. Maldaresti, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (330,'Maramures','Barsana, com. Barsana, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (331,'Salaj','Bezded, com. Garbou, jud. Salaj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (332,'Sibiu','Sibiel, com. Saliste, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (333,'Marginimea Sibiului','Fantanele, com. Saliste, jud. Sibiu');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (334,'Gorj','orasul Targu Carbunesti, jud. Gorj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (335,'Bihor','Campanii de Sus, com. Campani, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (336,'Sebes','Barzava, com. Sugag, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (337,'Arges','Hartiesti, com. Hartiesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (338,'Arges','Schitu, com. Nicolae Balcescu, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (339,'Tara Hategului','Almasu Mic de Munte, com. Balsa, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (340,'Tara Hategului','Serel, com. Pui, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (341,'Arges','Mosteni-Greci, com. Botesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (342,'Zarand','Baia de Cris, com. Baia de Cris, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (343,'Arges','Suici, com. Suici, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (344,'Muntii Apuseni','Metes, com. Metes, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (345,'Tara Bihorului','Campanii de Sus, com. Campani, jud. Bihor');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (346,'Muscel','Stanesti, com. Stanesti, jud. Arges');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (347,'Podisul Central Moldovenesc','Curteni, com. Oltenesti, jud. Vaslui');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (348,'Lapus','Buteasa, com. Somcuta Mare, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (349,'Bargaie','Tiha Bargaului, com. Josenii Bargaului, jud. Bistrita Nasaud');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (350,'Tara Oasului','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (351,'Gorj','Ceauru, com. Balesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (352,'Muntii Apuseni','com. Lupsa, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (353,'Campia  Transilvaniei','Geaca, com. Geaca, jud. Cluj');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (354,'Arad','Capalnic, com. Birchis, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (355,'Arad','Bata, com. Bata, jud. Arad');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (356,'Faget','Jupanesti, com. Faget, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (357,'Caransebes','Cavaran, com. Constantin Daicoviciu, jud. Caras Severin');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (358,'Faget','Topla, com. Manastiur, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (359,'Lugoj','Babsa, Colonia maghiara, com. Belint, jud. Timis');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (360,'Maramures','com. Giulesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (361,'Maramures','com. Poienile de sub munte, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (362,'Tinutul Secuiesc','Barzava, com. Frumoasa, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (363,'Maramures','Sieu, com. Rozavlea, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (364,'Tinutul Secuiesc','Cozmeni, com. Sanmartin, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (365,'Tinutul Secuiesc','com. Plaiesii de Jos, jud. Harghita');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (366,'Vrancea','Dragosloveni, Dragosloveni, com. Soveja, jud. Vrancea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (367,'Muntii Apuseni','Valea Mica; orasul Zlatna, Valea Mica, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (368,'Maramures','com. Bogdan Voda, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (369,'Maramures','Feresti, com. Calinesti, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (370,'Maramures','com. Sghet, jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (371,'Humor','com. Manastirea Humorului, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (372,'Radauti','Volovat, com. Volovat, jud. Suceava');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (373,'Tinutul Secuiesc','Cernat, com. Cernat, jud. Covasna');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (374,'Tinutul Secuiesc','Chiojd, com. Chiojd, jud. Buzau');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (375,'Sebes','Capalna, Muntele Puru, com. Sasciori, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (376,'Valcea','Cioboti, com. Olanu, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (377,'Valcea','Cheia; orasul Baile Olanesti, Valea Cheii, jud. Valcea');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (378,'Muntii Apuseni','Rosia Montana, com. Rosia Montana, jud. Alba');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (379,'Dobrogea de sud','Curcani, com. Cobadin, jud. Constanta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (380,'Maramures','jud. Maramures');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (381,'Zarand','Steia, com. Tomesti, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (382,'necunoscuta','necunoscuta');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (383,'Prahova','jud. Prahova');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (384,'Zarand','Luncoiu de Sus, Dvoiesti, com. Luncoiu de Jos, jud. Hunedoara');
Insert into locatii (ID_LOCATIE,ZONA_PROVENIENTA,LOCALITATE_PROVENIENTA) values (385,'Lipova','Bata, com. Bata, jud. Arad');